### ISSUE TITLE
Rename modules

### ISSUE THREAD

**Issue by sidvishnoi** [jatin69/statistical_calculator#4]
Instead of using module1, module2..., use descriptive names as used in documentation.
like `predictive_analysis.r` instead of `module2.r`
Helps in legibility, without going though documentation or code.
As you add more modules, it won't be easy to remember their numbers, so names would be better.

**Comment by jatin69** [comment]
I agree. 
But while development it was just easier for me to track the modules by their number.
Renaming them now would require changing a few other files as well, a few includes and all.
Also, this is done for now. Not in active development, so no more new modules.
